### PR TITLE
Convert None to Env.null

### PR DESCRIPTION
**Pull request by smartycope**

### CODE REVIEW

**Comment by Lonami** [comment]
Nice and simple.

**Comment by Lonami** [comment]
It seems this PR made CI unhappy after being merged due to formatting. So probably any new ones will be red too.

**Comment by smartycope** [comment]
I made a bunch of PRs at once, I may have forgotten to format one of them when splitting them up. There's a good chance one of the others will fix it.

**Comment by JeanJPNM** [comment]
I went through Mindustry's source code and couldn't find a place where `@null` is defined. While it has the same behavior during runtime since uninitualized variables are set to `null`, it may be misleading to use a variable that is not defined instead of directly using `null`.

**Comment by smartycope** [comment]
Oh, really? I've been using @null for my programs, but I guess that makes sense. Is `null` a "proper" null value, as opposed to `@null`? Would there even be such a variable, if uninitialized variables act the same way?

**Comment by Lonami** [comment]
Judging by https://github.com/Anuken/Mindustry/blob/0b19379b8c982f752ae3e4a4f8d2ee6141716e28/core/src/mindustry/logic/GlobalVars.java#L55, yeah, maybe it's just `null`.

**Pull request merged**
