### PR TITLE
Vector line draw functions

### LINKED ISSUE #35: Vectorize coordinates in draw commands?
Draw commands often refer to paired x,y values.  I've now mostly finished vectorized operations, including the ability to "unpack" vectors into commands like `dst()`, `atan2()` and `Unit.move_to()` that require x and y as separate operands in a single mlog instruction.  Should I use this same machinery for draw commands?  This would provide consistency, and also make some mathematical operations involving drawing a bit easier to perform: e.g., the midpoint between points A and B is (A+B)/2.  It would however make raw draw commands a tiny bit more cluttered, e.g. `draw.line( [0,0], [10,10] )` rather than `draw.line( 0,0,10,10 )`, though arguably these cluttering brackets actually make it more readable.

### PR DESCRIPTION
**Pull request by Leo-MathGuy**
`Screen.deg_line(x0, y0, degrees, magnitude)` -> Line with origin, degrees, and magnitude
`Screen.rad_line(x0, y0, radians, magnitude)`   -> Line with origin, radians, and magnitude

Partially fixes #35 but wont be fully fixed until lists get added

This might be useful for game design, animations, and if someone decides to recreate a ti-84 in mindustry

Also fixes a small bug in sorted config test file

### CODE REVIEW

**Review by Lonami — COMMENTED** [review]
[`pyndustri.pyi`](https://github.com/Lonami/pyndustric/blob/master/pyndustri.pyi) should be updated to explain what these do.

**Comment by Leo-MathGuy** [comment]
Ok going to do that

**Comment by Leo-MathGuy** [comment]
Done

**Review by Lonami — COMMENTED** [review]
Thanks. These functions only work with literals, and won't work with runtime variable values, right? So I'm wondering how useful are they, in practice?

**Comment by Leo-MathGuy** [comment]
Hmmm, I think its like that because it does the trig calculations during compilation of the program.
Is there a was in ast to get the value of a? (like *a in C to get the value of the variable from pointer a)

Like
`a = 50
b = 50

for i in range(0, 360):
    Screen.deg_line(a, b, i, 10)

Screen.flush()`

Because the trig calculations are done during compilation, it tries to use "a" as the x0, not the value of a.

**Comment by Leo-MathGuy** [comment]
Because of that its useless for now

**Comment by Leo-MathGuy** [comment]
Like is you do a/2 it tries to use "__pyc_tmp_3" (string) as x0

**Comment by Leo-MathGuy** [comment]
@Lonami Is there a way in ast to check if a variable is a literal or variable name? And how to get the value of that variable?

**Comment by Lonami** [comment]
The value of variables is calculated while Mindustry runs the program. You cannot get it from the compiler, because the value may come from a sensor (such as reading how many items a container has).

The only way is to do the calculations inside Mindustry too.

[Constant folding](https://en.wikipedia.org/wiki/Constant_folding), which is in a way what you did here, is definitely useful and could be applied thorough the compiler (at the cost of increased complexity). I'm not sure we should start doing that until we figure out a clean design, but this is a whole difḟerent topic entirely.

**Pull request closed without merging**
